-- Initial catalog only; historical demo traffic is deliberately reset to zero.
insert into public.tools (id,slug,name,category,description,status) values ('temp-mail','temp-mail','Temporary Email Generator','Email tools','Disposable inbox for one-time signups and testing flows.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('background-remover','background-remover','Background Remover','Image tools','Remove image backgrounds locally in the browser.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('pdf-merge','pdf-merge','PDF Merge','PDF tools','Merge PDF files without uploading any documents.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('image-to-pdf','image-to-pdf','Image to PDF Converter','PDF tools','Turn images into a single PDF document quickly.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('qr-code-generator','qr-code-generator','QR Code Generator','Generators','Create scannable QR codes for links and text.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('password-generator','password-generator','Password Generator','Generators','Generate secure random passwords with the right complexity.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('word-counter','word-counter','Word & Character Counter','Text tools','Get instant counts for words, characters, and reading time.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('json-formatter','json-formatter','JSON Formatter & Validator','Developer tools','Format, validate, and minify JSON in the browser.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('base64-tool','base64-tool','Base64 Encoder & Decoder','Developer tools','Encode and decode Base64 strings safely on-device.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('user-agent-generator','user-agent-generator','User Agent Generator','Developer tools','Generate realistic user-agent strings for testing.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('color-palette-generator','color-palette-generator','Color Palette Generator','Generators','Generate matching brand and UI color palettes.','active') on conflict (id) do nothing;
insert into public.tools (id,slug,name,category,description,status) values ('unit-converter','unit-converter','Unit Converter','Generators','Convert across common measurement units instantly.','active') on conflict (id) do nothing;
insert into public.posts (id,slug,title,excerpt,status,updated_at) values ('safe-temporary-email-signups','safe-temporary-email-signups','How to Use a Temporary Email Address Without Losing Messages You Actually Need','Disposable inboxes are useful for one-time signups, but they are not a replacement for real email addresses.','draft','2026-09-27') on conflict (id) do nothing;
insert into public.posts (id,slug,title,excerpt,status,updated_at) values ('removing-a-photo-background-guide','removing-a-photo-background-guide','Removing a Photo Background in Under a Minute','A quick guide to better background removal results using local browser tools.','draft','2026-09-27') on conflict (id) do nothing;
