const {test,before,after}=require('node:test');const assert=require('node:assert/strict');
process.env.ADMIN_EMAILS='owner@example.com';
let pending=true,updates=[];
const user=()=>({id:'u',email:'owner@example.com',email_confirmed_at:'2026-01-01',app_metadata:{password_setup_required:pending}});
const db={auth:{getUser:async token=>({data:{user:token==='invite'?user():null}}),admin:{updateUserById:async(id,attrs)=>{updates.push(attrs);pending=attrs.app_metadata.password_setup_required;return{data:{user:user()}};},signOut:async()=>({})}}};
const cp=require.resolve('../backend/src/lib/supabase');require.cache[cp]={id:cp,filename:cp,loaded:true,exports:{supabaseAdmin:db,createAuthClient:()=>({auth:{signInWithPassword:async()=>({data:{user:user(),session:{access_token:'password-session',expires_at:2000000000}}})}}),requireDatabase:(req,res,next)=>next()}};
const app=require('../backend/src/app');let server,base;
before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`;});after(()=>new Promise(r=>server.close(r)));
const setup=(token,password)=>fetch(base+'/api/admin/setup-password',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});
test('pending invitation cannot access admin even with owner email',async()=>{assert.equal((await fetch(base+'/api/admin/me',{headers:{Authorization:'Bearer invite'}})).status,403);});
test('password setup validates token and password before changing account',async()=>{assert.equal((await setup('bad','long-secure-password')).status,401);assert.equal((await setup('invite','short')).status,400);assert.equal(updates.length,0);});
test('valid invitation sets password, clears server-owned pending flag and issues a password session',async()=>{const r=await setup('invite','long-secure-password');assert.equal(r.status,200);const data=await r.json();assert.equal(data.admin,true);assert.equal(data.accessToken,'password-session');assert.equal(updates[0].app_metadata.password_setup_required,false);assert.equal((await setup('invite','another-password')).status,409);});
