const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const site = () => (process.env.SITE_URL || 'https://anviltools.vercel.app').replace(/\/$/, '');
function imageUrl(post) { return post.cover_image_id ? `${site()}/journal-images/${post.cover_image_id}` : null; }
function renderArticle(post) {
 const canonical = `${site()}/journal/${encodeURIComponent(post.slug)}`;
 const title = post.seo_title || post.title, description = post.seo_description || post.excerpt;
 const image = imageUrl(post);
 const ld = JSON.stringify({ '@context':'https://schema.org', '@type':'BlogPosting', headline:post.title, description, datePublished:post.published_at || undefined, dateModified:post.updated_at || undefined, image:image || undefined, mainEntityOfPage:canonical, keywords:(post.tags || []).join(', ') }).replace(/</g,'\\u003c');
 const paragraphs = (post.body || '').split(/\n\s*\n/).map(text => `<p>${escape(text).replace(/\n/g,'<br>')}</p>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | Anvil Tools</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}"><meta property="og:type" content="article"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}">${image?`<meta property="og:image" content="${escape(image)}"><meta property="og:image:alt" content="${escape(post.cover_alt)}">`:''}<meta name="twitter:card" content="${image?'summary_large_image':'summary'}"><link rel="icon" href="${site()}/assets/images/anvil-mark.svg"><link rel="stylesheet" href="${site()}/assets/css/style.css"><link rel="stylesheet" href="${site()}/assets/css/refinements.css"><link rel="stylesheet" href="${site()}/assets/css/design.css"><script type="application/ld+json">${ld}</script></head><body class="public-site"><a class="skip-link" href="#main-content">Skip to article</a><header class="site-header"><div class="header-row"><a class="logo" href="${site()}/"><img src="${site()}/assets/images/anvil-mark.svg" width="36" height="36" alt="">Anvil Tools</a><a href="${site()}/blog/index.html">All guides &#8594;</a></div></header><main class="wrap" id="main-content"><p class="breadcrumbs"><a href="${site()}/">Home</a> / <a href="${site()}/blog/index.html">Guides</a></p><article class="info-section published-article"><span class="eyebrow">${escape(post.category_slug || 'Guide')}</span><h1>${escape(post.title)}</h1><p class="lede">${escape(post.excerpt)}</p>${post.published_at?`<p class="small-note">Published <time datetime="${escape(post.published_at)}">${escape(post.published_at.slice(0,10))}</time></p>`:''}${image?`<img class="article-cover" src="${escape(image)}" alt="${escape(post.cover_alt)}">`:''}<div class="article-content">${paragraphs}</div><div class="chip-row">${(post.tags||[]).map(tag=>`<span class="chip">${escape(tag)}</span>`).join('')}</div></article></main><footer class="site-footer"><div class="wrap footer-bottom"><span>Developed by VelloxTech</span><a href="${site()}/contact.html">Contact</a><a href="${site()}/privacy-policy.html">Privacy policy</a></div></footer></body></html>`;
}
module.exports = { renderArticle, imageUrl, escape, site };
